import os
import re
import zipfile
import tempfile
import requests
import pandas as pd
import networkx as nx


def get_latest_biogrid_version():
    """
    Query BioGRID homepage and extract the newest release version.
    """

    url = "https://thebiogrid.org/"

    response = requests.get(url, timeout=30)
    response.raise_for_status()

    html = response.text

    # Match patterns like: version 5.0.257
    matches = re.findall(r"version\s+(\d+\.\d+\.\d+)", html, re.IGNORECASE)

    if not matches:
        raise RuntimeError("Could not determine latest BioGRID version")

    # Convert to sortable tuples
    versions = sorted(
        matches,
        key=lambda v: tuple(map(int, v.split("."))),
        reverse=True
    )

    return versions[0]


def add_latest_biogrid_interactions(G,interaction_types=None,verbose=True):
    """
    Add newest BioGRID interaction data to an existing NetworkX graph.

    Parameters
    ----------
    G : networkx.Graph
        Existing graph generated by grn_network.py

    interaction_types : list or None
        Optional filtering keywords for interaction type

    verbose : bool
        Print progress information

    Returns
    -------
    G : networkx.Graph
        Updated graph
    """

    version = get_latest_biogrid_version()

    biogrid_url = (
        f"https://downloads.thebiogrid.org/BioGRID/"
        f"Release-Archive/BIOGRID-{version}/"
        f"BIOGRID-ALL-{version}.mitab.zip"
    )

    if verbose:
        print(f"Latest BioGRID version detected: {version}")
        print(f"Download URL: {biogrid_url}")

    temp_dir = tempfile.mkdtemp()

    zip_path = os.path.join(temp_dir, "biogrid.zip")

    if verbose:
        print("Downloading BioGRID dataset...")

    r = requests.get(biogrid_url, stream=True, timeout=300)
    r.raise_for_status()

    with open(zip_path, "wb") as f:
        for chunk in r.iter_content(chunk_size=8192):
            f.write(chunk)

    if verbose:
        print("Extracting archive...")

    with zipfile.ZipFile(zip_path, "r") as z:
        z.extractall(temp_dir)

    mitab_file = None

    for root, _, files in os.walk(temp_dir):
        for fname in files:
            if fname.endswith(".mitab.txt"):
                mitab_file = os.path.join(root, fname)
                break

    if mitab_file is None:
        raise FileNotFoundError("MITAB file not found")

    if verbose:
        print(f"Reading: {mitab_file}")

    columns = [
        "ID_A", "ID_B",
        "Alt_A", "Alt_B",
        "Aliases_A", "Aliases_B",
        "Detection_Method",
        "Author",
        "Pubmed",
        "Tax_A",
        "Tax_B",
        "Interaction_Type",
        "Source_DB",
        "Interaction_ID",
        "Confidence"
    ]

    df = pd.read_csv(mitab_file, sep="\t", comment="#", header=None, names=columns, usecols=range(len(columns)),low_memory=False)

    if verbose:
        print(f"Loaded {len(df):,} interactions")


    # Optional interaction-type filtering
    if interaction_types is not None:

        mask = df["Interaction_Type"].astype(str).apply(
            lambda x: any(
                term.lower() in x.lower()
                for term in interaction_types
            )
        )

        df = df[mask]

        if verbose:
            print(f"Filtered to {len(df):,} selected interactions")

    def extract_gene_symbol(alias_field):

        if pd.isna(alias_field):
            return None

        entries = str(alias_field).split("|")

        for entry in entries:

            entry_lower = entry.lower()

            if "locuslink:" in entry_lower:
                return entry.split(":")[-1].upper()

            if "symbol:" in entry_lower:
                return entry.split(":")[-1].upper()

        first = entries[0]

        if ":" in first:
            return first.split(":")[-1].upper()

        return first.upper()

    added_edges = 0

    # Faster iteration
    for row in df.itertuples(index=False):

        gene_a = extract_gene_symbol(row.Aliases_A)
        gene_b = extract_gene_symbol(row.Aliases_B)

        if gene_a is None or gene_b is None:
            continue

        if gene_a == gene_b:
            continue

        if not G.has_node(gene_a):
            G.add_node(gene_a, source="BioGRID")

        if not G.has_node(gene_b):
            G.add_node(gene_b, source="BioGRID")

        if not G.has_edge(gene_a, gene_b):

            G.add_edge(
                gene_a,
                gene_b,
                interaction_source="BioGRID",
                biogrid_version=version,
                pubmed=row.Pubmed,
                interaction_type=row.Interaction_Type,
                detection_method=row.Detection_Method
            )

            added_edges += 1

    if verbose:
        print(f"Added {added_edges:,} BioGRID edges")

    return G

